version: v1

labels:
  - label: "feat"
    matcher:
      title: "^feat:.*"
      branch: "^feat/.*"
      commits: "^feat:.*"
  - label: dependabot
    matcher:
      title: "^chore(deps).*"
      branch: "^dependabot/.*"
      commits: "^chore(deps).*"
  - label: "fix"
    matcher:
      title: "^fix:.*"
      branch: "^fix/.*"
      commits: "^fix:.*"

  - label: "chore"
    matcher:
      title: "^chore(\\((deps|ci)\\))?:.*"
      branch: "^chore/.*"
      commits: "^chore(\\((deps|ci)\\))?:.*"

  - label: "docs"
    matcher:
      title: "^docs:.*"
      branch: "^docs/.*"
      commits: "^docs:.*"
      files: "^docs/.*"

  - label: "test:labeler"
    sync: true
    matcher:
      files: ".github/labeler.yml"

  - label: "test:dist"
    sync: true
    matcher:
      files: [ "dist/*" ]

  - label: "test:tests"
    sync: true
    matcher:
      files: [ "__tests__/matcher/**", "__tests__/*.ts", "tests/**" ]

  - label: "test:body"
    matcher:
      body: "(\\n|.)*- \\[x\\] test(\\n|.)*"

  - label: "test:comment"
    matcher:
      comment: "# \\[Codecov\\] .*"

  - label: "test:stale"
    matcher:
      comment: "/stale"

  - label: "test: s"
    sync: true
    matcher:
      files:
        count:
          gte: 1
          lte: 4

  - label: "test: m"
    sync: true
    matcher:
      files:
        count:
          gte: 5
          lte: 10

  - label: "test: l"
    sync: true
    matcher:
      files:
        count:
          gte: 11

  - label: "Maintainer"
    matcher:
      author:
        - RitheeshBaradwaj

  - label: "Owner"
    matcher:
      author: RitheeshBaradwaj

  - label: "branch: main"
    matcher:
      baseBranch: main

  - label: "branch: release"
    matcher:
      baseBranch: "^release/.*"

checks:
  - context: "Semantic Pull Request"
    url: "https://github.com/developers-cosmos/Mimasa/blob/main/.github/labeler.yml"
    description:
      success: Ready for review & merge.
      failure: Missing semantic label for merge.
    labels:
      any:
        - feat
        - fix
        - chore
        - docs

  - context: "Do Not Merge"
    url: "https://github.com/developers-cosmos/Mimasa/blob/main/.github/labeler.yml"
    description: "Disable merging when 'DO NOT MERGE' label is set"
    labels:
      none:
        - "DO NOT MERGE"

  - context: "Label verification"
    description: "Ensuring appropriate label is assigned to pull requests and issues"
    labels:
      any:
        - feat
        - fix
        - chore
        - docs
