ci/cd:
  - .github/workflows/*

release:
  - name: Release
    branch: ['release/*', 'hotfix/**']
    labels: [ 'Release' ]

docs:
  - name: Documentation
    files:
      - README.md
      - ./*.md
      - docs/**
    branch: 'docs/*'
    pr:
      title:
        - 'docs:*'
      body:
        - any: [ '*document*' ]
    commits:
      title:
        - 'docs:*'
    labels: [ 'Documentation' ]

test:
  - name: Testing
    files:
      - tests/**
    branch: 'test/*'
    pr:
      title:
        - 'test:*'
      body:
        - any: [ '*test*' ]
          all: [ '*bug*' ]
    commits:
      title:
        - 'test:*'
    labels: [ 'Testing' ]

feat:
  - name: Feature
    branch: 'feat/*'
    pr:
      title:
        - 'feat:*'
      body:
        - any: [ 'feature' ]
    commits:
      title:
        - 'feat:*'
    labels: [ 'Feature' ]

bug:
  - name: Bug Fix
    branch: ['bug/*', 'fix/*']
    pr:
      title:
        - 'bug:*'
      body:
        - any: [ 'bug', 'fix' ]
    commits:
      title:
        - 'bug:*'
    labels: [ 'Bug Fix' ]

refactor:
  - name: Refactor
    branch: 'chore/'
    pr:
      title:
        - 'refactor:*'
      body:
        - any: [ 'refactor' ]
    commits:
      title:
        - 'refactor:*'
    labels: [ 'Refactor' ]

chore:
  - name: Chore
    branch: 'chore/*'
    pr:
      title:
        - 'chore:*'
      body:
        - any: [ 'chore' ]
    commits:
      title:
        - 'chore:*'
    labels: [ 'Chore' ]
