repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

# -   repo: https://github.com/psf/black
#     rev: '23.9.1'
#     hooks:
#     -   id: black
#     -   id: black

# -   repo: https://github.com/pycqa/isort
#     rev: 5.12.0
#     hooks:
#     -   id: isort

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.942
#     hooks:
#     - id: mypy
#       args: ["--install-types", "--non-interactive", "--ignore-missing-imports"]

# -   repo: https://github.com/hadialqattan/pycln
#     rev: 'v2.2.2'
#     hooks:
#     -   id: pycln
#         args: ['.', "--all"]

# -   repo: https://github.com/pycqa/pydocstyle
#     rev: '6.3.0'
#     hooks:
#     -   id: pydocstyle
#         args: ['.']
