@startuml Mimasa Core Component

Title: Video Processing

actor User

User -> MimasaApp: Open the Mimasa app
MimasaApp -> User: Request access to media
User -> MimasaApp: Grant necessary permissions
User -> MimasaApp: Upload video
User -> MimasaApp: Submit a request (language and video input)
MimasaApp -> VideoProcessor: Send video for processing

VideoProcessor -> VideoProcessor: Extract audio from video
VideoProcessor -> AudioExtractor: send extracted audio
VideoProcessor -> VideoPreprocessor: Send video for pre-processing
VideoPreprocessor -> VideoPreprocessor: pre-processing
VideoPreprocessor -> FeatureExtractor: Extract facial features
FeatureExtractor -> EmotionIdentifier: Identify the user's emotions based on facial expressions and lip/face movements
EmotionIdentifier -> AudiAndVideoSyncer : send lip/face movement data for further sync

Note over VideoProcessor: Wait for audio processing to be completed

Title: Audio Translation

AudioExtractor -> AudioPreprocessor: Extracted audio from video
AudioPreprocessor -> AudioSeparator: Preprocessed audio
AudioSeparator -> PostProcessor: Separated vocals and background music
PostProcessor -> PostProcessor: Remove HF/noise if needed
PostProcessor -> VocalDeterminer: sending vocals
VocalDeterminer -> VocalDeterminer: Determine the portion of vocals in the audio
VocalDeterminer -> SpeechToTextTranslator: Translate audio/vocals to text in the desired language
SpeechToTextTranslator -> TextToSpeechTranslator: Convert text to audio/speech
TextToSpeechTranslator -> AudiAndVideoSyncer: sending translated audio with vocals
PostProcessor -> PostProcessor: Overlay translated vocals with music audio in determined vocal positions
PostProcessor -> AudiAndVideoSyncer: sending translated audio

Note over VideoProcessor: Resume processing

Title: Video Translation

actor User

VideoProcessor -> MovementSynchronizer: Synchronize lip/face movements with translated audio
MovementSynchronizer -> LipMovementSynchronizer: finding lip movements
MovementSynchronizer -> FaceMovementSynchronizer: finding face movements
MovementSynchronizer -> AudiAndVideoSyncer: Create a final video with translated audio

AudiAndVideoSyncer -> AudiAndVideoSyncer: sync translated audio and video
AudiAndVideoSyncer -> VideoOutput: Create Translation and send video output
VideoOutput -> MimasaApp: Send output video to user

MimasaApp -> User: Notify the user of the completion
MimasaApp -> User: Display translated video on screen
User -> MimasaApp: Option to select a different language for translation
User -> MimasaApp: Option to save a translation for later reference
User -> MimasaApp: Option to share the translation with others

@enduml
