name: Labeler

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Label PR
      uses: peter-evans/labeler@v1.6.0
      with:
        args: label --config .github/labeler.yml
