name: Labeler

on: [pull_request]

jobs:
  add-label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.x

    - name: Add label based on modified paths
      uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true

    - name: Add label based on branch or PR title
      id: add_label
      run: |
        python .github/add_labels.py
        exit_code=$?

    - name: Add label to PR
      if: steps.add_label.outputs.exit_code == 0
      uses: actions/github-script@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        script: |
          const labelsString = ${{ env.LABELS}}
          const labels = labelsString.split(' ')
          github.issues.addLabels({ issue_number: context.issue.number, labels: labels })
