name: Labeler

on:
  pull_request:
    types: [opened, edited, synchronized]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - name: Label PR
      uses: actions/labeler@v4
      with:
        labels: |
          ci/cd: .github/workflows/*
          release:
            - branch: ['release/**', 'hotfix/**']
          docs:
            - README.md
            - ./*.md
            - docs/**
            - branch: 'docs/'
            - pr:
              title:
                - 'docs:'
              body:
                - any: ['document']
              commits:
                title:
                  - 'docs:'
          test:
            - tests/**
            - branch: 'test/'
            - pr:
              title:
                - 'test:'
              body:
                - any: ['test']
              commits:
                title:
                  - 'test:'
          feat:
            - branch: 'feat/'
            - pr:
              title:
                - 'feat:'
              body:
                - any: ['feature']
              commits:
                title:
                  - 'feat:'
          bug:
            - branch: ['bug/', 'fix/']
            - pr:
              title:
                - 'bug:'
              body:
                - any: ['bug', 'fix']
              commits:
                title:
                  - 'bug:'
          refactor:
            - branch: 'chore/'
            - pr:
              title:
                - 'refactor:'
              body:
                - any: ['refactor']
              commits:
                title:
                  - 'refactor:'
          chore:
            - branch: 'chore/'
            - pr:
              title:
                - 'chore:'
              body:
                - any: ['chore']
              commits:
                title:
                  - 'chore:'
