name: Labeler

on: [pull_request]

jobs:
  add-label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.x

    - name: Add label based on modified paths
      uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true

    - name: Add label based on branch or PR title
      id: add_labels
      run: |
        echo "BRANCH_NAME=$(echo "${{ github.ref  }}" | sed "s/refs\/heads\///")" >> $GITHUB_ENV
        echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
        python .github/add_labels.py
        exit_code=$?

    - name: Add label to PR
      if: steps.add_labels.outputs.exit_code == 0
      uses: actions/github-script@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        script: |
          var fs = require('fs');
          const fileContents = fs.readFileSync('labels.txt', 'utf-8');
          const labels = fileContents.split('\n');
          github.issues.addLabels({ issue_number: context.issue.number, labels: labels })
