name: Fix Pylint Errors with Black

on:
  push:
    branches:
      - '!main'
  pull_request:

jobs:
  fix_pylint_errors:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.x

    - name: Install dependencies
      run: |
        pip install black pylint

    - name: Run Black
      run: |
        black .

    - name: Check for Pylint errors
      run: |
        pylint --rcfile=.pylintrc --exit-zero --persistent=n --output-format=html --reports=yes --files-output=yes --reports-dir=pylint_reports $(git ls-files '*.py')

    - name: Upload pylint reports after fixing errors
      uses: actions/upload-artifact@v2
      with:
        name: pylint_reports
        path: pylint_reports

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: pylint_reports

    - name: Commit changes
      id: commit_changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add .
        if [ -z "$(git diff-index --cached --quiet HEAD --)" ]; then
          echo "No changes to commit."
          exit 0
        fi
        git commit -m "Fix Pylint errors with Black"

    - name: Push changes
      if: steps.commit_changes.outputs.exit_code != 0
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - name: Comment on Pull Request
      if: success() && steps.commit_changes.outputs.exit_code != 0 && [ "${{ github.event_name }}" == "pull_request" ]
      uses: actions/github-script@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        script: |
          const result = await github.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            head: context.sha,
          });

          if (result.data.length) {
            const pullRequest = result.data[0];
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pullRequest.number,
              body: 'Linting errors observed and fixed 🎉. Please pull the latest changes!!!',
            });
          }
