name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Tag
      id: tag
      run: echo "::set-output name=tag::$(echo $GITHUB_REF | cut -d '/' -f 3)"

    - name: Get Changelog
      id: changelog
      run: echo "::set-output name=changelog::$(cat CHANGELOG.md)"

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        release_name: "Release ${{ steps.tag.outputs.tag }}"
        body: ${{ steps.changelog.outputs.changelog }}
